create table if not exists engines
(
    id integer generated by default as identity
        primary key
);

create table if not exists cars
(
    id        integer generated by default as identity
        primary key,
    engine_id integer
    constraint engine_id_fk
            references engines
);

create table if not exists drivers
(
    id integer generated by default as identity
        primary key
);

create table if not exists history_owner
(
    driver_id integer not null
            references cars,
    car_id    integer not null
            references drivers,
    primary key (driver_id, car_id)
);
